//go:build exclude

package main

import (
	"time"

	"fyne.io/fyne/v2"
	"fyne.io/fyne/v2/app"

	"apptrix.org/components/widget/chat"
)

func main() {
	a := app.NewWithID("dev.chat")
	w := a.NewWindow("chat-dev")

	a.Settings().SetTheme(&myTheme{})

	src := newDemoMessageSource(20)

	wc := chat.New(src)
	wc.ScrollToBottom()

	go src.AutoGenerateDemoData(wc, 5*time.Second)

	w.SetContent(wc)
	w.Resize(fyne.NewSize(400, 400))
	w.ShowAndRun()
}
