//go:build exclude

package main

import (
	"fmt"
	"math/rand"
	"strings"
	"time"

	"fyne.io/fyne/v2"
	"gopkg.in/loremipsum.v1"

	"apptrix.org/components/widget/chat"
)

type demoMessageSource struct {
	msgs    []chat.Message
	pending chat.Message
	gen     *loremipsum.LoremIpsum
}

func newDemoMessageSource(initialSize int) *demoMessageSource {
	src := &demoMessageSource{}
	src.gen = loremipsum.New()

	sentAt := time.Date(2026, time.February, 1, 0, 0, 0, 0, time.UTC)
	for n := 0; n < initialSize; n++ {
		src.msgs = append(src.msgs, chat.NewMessage(
			fmt.Sprintf("msgid-%03d", n),
			"sndrid-001",
			"Someone",
			src.gen.Sentences(1),
			sentAt,
			false,
		))
		sentAt = sentAt.Add(time.Hour)
	}

	return src
}

func (src *demoMessageSource) Length() int {
	n := len(src.msgs)
	if src.pending == nil {
		return n
	}
	return n+1
}

func (src *demoMessageSource) GetItem(n int) chat.Message {
	if n == len(src.msgs) && src.pending != nil {
		return src.pending
	}
	if n < 0 || n >= len(src.msgs) {
		return nil
	}
	return src.msgs[n]
}

func (src *demoMessageSource) send(msg chat.Message) {
	src.pending = nil
	src.msgs = append(src.msgs, msg)
}

func (src *demoMessageSource) setPending(msg chat.Message) {
	src.pending = msg
}

func firstup(s string) string {
	if len(s) < 1 {
		return s
	}
	return strings.ToTitle(s[:1]) + s[1:]
}

func (src *demoMessageSource) AutoGenerateDemoData(wc *chat.Chat, pause time.Duration) {
	steps := []string{".", "..", "..."}
	for {
		time.Sleep(pause)

		words := src.gen.WordList(2 + rand.Intn(10))

		msgId := "msgxxxx"
		senderId := "sndyyyyy"
		senderName := firstup(src.gen.Word())
		for n := range words {
			src.setPending(chat.NewMessage(
				msgId,
				senderId,
				senderName,
				steps[n%len(steps)],
				time.Now(),
				false,
			))
			fyne.Do(func() {
				wc.Refresh()
				wc.ScrollToBottom()
			})
			time.Sleep(400 * time.Millisecond)
		}

		src.send(chat.NewMessage(
			msgId,
			senderId,
			senderName,
			strings.Join(words, " ")+".",
			time.Now(),
			false,
		))

		fyne.Do(func() {
			wc.Refresh()
			wc.ScrollToBottom()
		})
	}
}
