package main

import (
	"fmt"
	"math/rand"
	"strings"
	"time"

	"fyne.io/fyne/v2"

	"apptrix.org/components/widget/chat"
)

var lorem = strings.Split("lorem ipsum dolor sit amet consectetur adipiscing"+
	" elit sed do eiusmod tempor incididunt ut labore et dolore magna"+
	" aliqua ut enim ad minim veniam quis nostrud exercitation ullamco"+
	" laboris nisi ut aliquip ex ea commodo consequat duis aute irure dolor"+
	" in reprehenderit in voluptate velit esse cillum dolore eu fugiat"+
	" nulla pariatur excepteur sint occaecat cupidatat non proident sunt"+
	" in culpa qui officia deserunt mollit anim id est laborum", " ")

func genSentences(n int) string {
	r := make([]string, n)
	for i := 0; i < n; i++ {
		w := 3 + rand.Intn((len(lorem)/3)-3)
		x := make([]string, w)
		for j := 0; j < w; j++ {
			x[j] = lorem[rand.Intn(len(lorem))]
		}
		r[i] = strings.Join(x, " ") + "."
	}
	return strings.Join(r, " ")
}

func genWord() string {
	return lorem[rand.Intn(len(lorem))]
}

func genWordList(n int) []string {
	r := make([]string, n)
	for i := 0; i < n; i++ {
		r[i] = lorem[rand.Intn(len(lorem))]
	}
	return r
}

type demoMessageSource struct {
	msgs    []chat.Message
	pending chat.Message
}

func newDemoMessageSource(initialSize int) *demoMessageSource {
	src := &demoMessageSource{}

	sentAt := time.Date(2026, time.February, 1, 0, 0, 0, 0, time.UTC)
	for n := 0; n < initialSize; n++ {
		senderId := "sndr-1"
		senderName := "Someone"
		isMine := n%3 == 0
		if isMine {
			senderId = "sndr-2"
			senderName = "Me"
		}
		src.msgs = append(src.msgs, chat.NewMessage(
			fmt.Sprintf("msgid-%03d", n),
			senderId,
			senderName,
			genSentences(1),
			sentAt,
			isMine,
		))
		sentAt = sentAt.Add(time.Hour)
	}

	return src
}

func (src *demoMessageSource) Length() int {
	n := len(src.msgs)
	if src.pending == nil {
		return n
	}
	return n + 1
}

func (src *demoMessageSource) GetMessage(n int) chat.Message {
	if n == len(src.msgs) && src.pending != nil {
		return src.pending
	}
	if n < 0 || n >= len(src.msgs) {
		return nil
	}
	return src.msgs[n]
}

func (src *demoMessageSource) send(msg chat.Message) {
	src.pending = nil
	src.msgs = append(src.msgs, msg)
}

func (src *demoMessageSource) setPending(msg chat.Message) {
	src.pending = msg
}

func lcfirst(s string) string {
	if len(s) < 1 {
		return s
	}
	return strings.ToTitle(s[:1]) + s[1:]
}

func (src *demoMessageSource) autoGenerateDemoData(wc *chat.Chat, pause time.Duration) {
	steps := []string{".", "..", "..."}
	for {
		time.Sleep(pause)

		words := genWordList(2 + rand.Intn(10))

		msgId := "msgxxxx"
		senderId := "sndyyyyy"
		senderName := lcfirst(genWord())
		for n := range words {
			src.setPending(chat.NewMessage(
				msgId,
				senderId,
				senderName,
				steps[n%len(steps)],
				time.Now(),
				false,
			))
			fyne.Do(func() {
				wc.Refresh()
			})
			time.Sleep(400 * time.Millisecond)
		}

		src.send(chat.NewMessage(
			msgId,
			senderId,
			senderName,
			strings.Join(words, " ")+".",
			time.Now(),
			false,
		))

		fyne.Do(func() {
			wc.Refresh()
		})
	}
}
